In [20]:
import os
import numpy as np
import pandas as pd
from dotenv import load_dotenv

In [31]:
load_dotenv()

data_dir = os.path.abspath(os.getenv('BITS_DATA_DIR_PYTHON'))
DATASET_NAME = 'hour.csv'

__location__ = os.path.realpath(data_dir)
for dirname, _, filenames in os.walk(__location__):
    for filename in filenames:
        if filename == DATASET_NAME:
            input_data = os.path.join(dirname, filename)
            break

try:
    assert input_data is not None
except:
    raise Exception(f'Input dataset {DATASET_NAME} not found.')

In [32]:
bikes = pd.read_csv(input_data)
bikes.head()

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,3,13,16
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,8,32,40
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,5,27,32
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,3,10,13
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0,0,1,1